### ISSUE TITLE
TODO for initial release

### ISSUE THREAD

**Issue by AntoninCamus** [Insalan-EquipeTechnique/insalan-langate2000#3]
- Management page
  - [x] Add search fields 
    - by player
    - by tournament
    - by type of user

  - Add columns :
    - [ ] flow used by players [Medium priority]
    - [x] replace "inscription tournois" by "tournois" [Medium priority]
  - [x] Add buton to regenerate passwords

  - Registration page
    - [x] Add UI (modal window) and link it to backend 
    - [x] Add to model user type "coach" [Medium priority]
    - [x] Improve chain user registration
    - [x] Add asterix to hint which fields are needed

- [x] Add a detail player page or merge it to device page

- Landing page
  - [x] Add devices to network lib
  - [x] Add a visual logo to clarify connection state
![image](https://user-images.githubusercontent.com/9219052/49176130-71f7e100-f34a-11e8-8b51-91e6da7fed94.png)
  - [x] Display advices only in case of errors

- Widgets [Priorité : Basse ]
  - [x] Make pizza widget modular
  - [ ] Make a discord widget (activated in mini)

- Add a mininsalan config 
  - [x] without possibility to register more than 1 device
  - [x] with good schedules for pizzas
  - [ ] with discord widget

- [ ] Add unit tests [Medium priority]

**Comment by AntoninCamus** [comment]
Mis à jour suite à réunion avec @darkgallium

**Comment by AntoninCamus** [comment]
Mise à jour suite à la mini de Noël.
